apiVersion: v1
kind: ConfigMap
metadata:
  name: gophprofile-config
  namespace: gophprofile
data:
  SERVER_ADDRESS: "0.0.0.0:8080"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "goph-profile"
  MINIO_USE_SSL: "false"
  OTEL_SERVICE_NAME: "GophProfile"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=kubernetes"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gophprofile-worker-config
  namespace: gophprofile
data:
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "goph-profile"
  MINIO_USE_SSL: "false"
  OTEL_SERVICE_NAME: "GophProfile-worker"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=kubernetes"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
