apiVersion: v2
name: gophprofile
description: Avatar upload/serve service (Go + chi + Postgres + MinIO + RabbitMQ)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords: [avatars, gophprofile]
maintainers:
  - name: GophProfile
