{{- include "gophprofile.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophprofile.server.name" . }}-config
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophprofile.worker.name" . }}-config
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.workerConfig }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
