{{- if .Values.server.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gophprofile.server.name" . }}
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gophprofile.server.name" . }}
  minReplicas: {{ .Values.server.hpa.minReplicas }}
  maxReplicas: {{ .Values.server.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: {{ .Values.server.hpa.targetCPUUtilizationPercentage }} }
    - type: Resource
      resource:
        name: memory
        target: { type: Utilization, averageUtilization: {{ .Values.server.hpa.targetMemoryUtilizationPercentage }} }
  behavior:
    scaleDown: { stabilizationWindowSeconds: 300 }
    scaleUp:   { stabilizationWindowSeconds: 30 }
{{- end }}
{{- if .Values.worker.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gophprofile.worker.name" . }}
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gophprofile.worker.name" . }}
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: {{ .Values.worker.hpa.targetCPUUtilizationPercentage }} }
{{- end }}
