apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.server.name" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app: gophprofile-server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: gophprofile-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - { name: http,    port: {{ .Values.server.service.httpPort }}, targetPort: http }
    - { name: metrics, port: {{ .Values.server.metricsPort }},      targetPort: metrics }
