apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gophprofile.server.name" . }}
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gophprofile.worker.name" . }}
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
automountServiceAccountToken: false
