apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: gophprofile
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gophprofile
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:18.0
          env:
            - { name: POSTGRES_USER, value: postgres_user }
            - { name: POSTGRES_PASSWORD, value: postgres_password }
            - { name: POSTGRES_DB, value: postgres_db }
            - { name: PGDATA, value: /var/lib/postgresql/data/pgdata }
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres_user", "-d", "postgres_db"]
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gophprofile
spec:
  selector: { app: postgres }
  ports:
    - port: 5432
      targetPort: 5432
