// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	broker "GophProfile/internal/broker"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Publisher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishDelete provides a mock function with given fields: ctx, event
func (_m *Publisher) PublishDelete(ctx context.Context, event broker.AvatarDeleteEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, broker.AvatarDeleteEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishUpload provides a mock function with given fields: ctx, event
func (_m *Publisher) PublishUpload(ctx context.Context, event broker.AvatarUploadEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, broker.AvatarUploadEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
