// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "GophProfile/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// CreateNewAvatarRecord provides a mock function with given fields: ctx, userID, fileName, mimeType, size
func (_m *Storage) CreateNewAvatarRecord(ctx context.Context, userID string, fileName string, mimeType string, size int64) (*model.Avatar, error) {
	ret := _m.Called(ctx, userID, fileName, mimeType, size)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewAvatarRecord")
	}

	var r0 *model.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (*model.Avatar, error)); ok {
		return rf(ctx, userID, fileName, mimeType, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) *model.Avatar); ok {
		r0 = rf(ctx, userID, fileName, mimeType, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = rf(ctx, userID, fileName, mimeType, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx
func (_m *Storage) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAvatarS3Key provides a mock function with given fields: ctx, avatarID, s3Key
func (_m *Storage) UpdateAvatarS3Key(ctx context.Context, avatarID string, s3Key string) error {
	ret := _m.Called(ctx, avatarID, s3Key)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatarS3Key")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, avatarID, s3Key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
